version: '3'
services:
  app:
    build: .
    ports:
      - "${REACT_PORT}:${REACT_PORT}"  # React
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: >
      bash -c "npm install && npm run dev"
